version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx/Dockerfile
    ports:
      - '8080:80'
    volumes:
      - ./Dockerfile-nginx/nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www/html
    depends_on:
      - php5.6-fpm
      - php7.0-fpm
      - php7.1-fpm
      - php7.2-fpm
      - php7.3-fpm
      - php7.4-fpm
      - php8.0-fpm
      - php8.1-fpm
      - php8.2-fpm


  php5.6-fpm:
    build:
      args:
        IMAGE: php:5.6-fpm-alpine
        PHP_BUILD_VERSION: 5.6

        WORKDIR: /builder
        PHP_EXTENSION_DIR: '/usr/local/lib/php/extensions/no-debug-non-zts-20131226'
      context: .
      dockerfile: Dockerfiles-php/5.6/Dockerfile-alpine
    volumes:
      - ./:/var/www/html

  php7.0-fpm:
    build:
      args:
        IMAGE: php:7.0-fpm-alpine
        PHP_BUILD_VERSION: 7.0

        WORKDIR: /builder
        PHP_EXTENSION_DIR: '/usr/local/lib/php/extensions/no-debug-non-zts-20151012'
      context: .
      dockerfile: Dockerfiles-php/7.0/Dockerfile-alpine
    volumes:
      - ./:/var/www/html

  php7.1-fpm:
    build:
      args:
        IMAGE: php:7.1-fpm-alpine
        PHP_BUILD_VERSION: 7.1

        WORKDIR: /builder
        PHP_EXTENSION_DIR: '/usr/local/lib/php/extensions/no-debug-non-zts-20160303'
      context: .
      dockerfile: Dockerfiles-php/7.0/Dockerfile-alpine
    volumes:
      - ./:/var/www/html

  php7.2-fpm:
    build:
      args:
        IMAGE: php:7.2-fpm-alpine
        PHP_BUILD_VERSION: 7.2
        WORKDIR: /builder
        PHP_EXTENSION_DIR: '/usr/local/lib/php/extensions/no-debug-non-zts-20160303'
      context: .
      dockerfile: Dockerfiles-php/7.2/Dockerfile-alpine
    volumes:
      - ./:/var/www/html

  php7.3-fpm:
    build:
      args:
        IMAGE: php:7.3-fpm-alpine
        PHP_BUILD_VERSION: 7.3
        WORKDIR: /builder
        PHP_EXTENSION_DIR: '/usr/local/lib/php/extensions/no-debug-non-zts-20160303'
      context: .
      dockerfile: Dockerfiles-php/7.3/Dockerfile-alpine
    volumes:
      - ./:/var/www/html

  php7.4-fpm:
    build:
      args:
        IMAGE: php:7.4-fpm-alpine
        PHP_BUILD_VERSION: 7.4
        WORKDIR: /builder
        PHP_EXTENSION_DIR: '/usr/local/lib/php/extensions/no-debug-non-zts-20160303'
      context: .
      dockerfile: Dockerfiles-php/7.4/Dockerfile-alpine
    volumes:
      - ./:/var/www/html

  php8.0-fpm:
    build:
      args:
        IMAGE: php:8.0-fpm-alpine
        PHP_BUILD_VERSION: 8.0
        WORKDIR: /builder
        PHP_EXTENSION_DIR: '/usr/local/lib/php/extensions/no-debug-non-zts-20160303'
      context: .
      dockerfile: Dockerfiles-php/8.0/Dockerfile-alpine
    volumes:
      - ./:/var/www/html

  php8.1-fpm:
    build:
      args:
        IMAGE: php:8.1-fpm-alpine
        PHP_BUILD_VERSION: 8.1
        WORKDIR: /builder
        PHP_EXTENSION_DIR: '/usr/local/lib/php/extensions/no-debug-non-zts-20160303'
      context: .
      dockerfile: Dockerfiles-php/8.1/Dockerfile-alpine
    volumes:
      - ./:/var/www/html

  php8.2-fpm:
    build:
      args:
        IMAGE: php:8.2-fpm-alpine
        PHP_BUILD_VERSION: 8.2
        WORKDIR: /builder
        PHP_EXTENSION_DIR: '/usr/local/lib/php/extensions/no-debug-non-zts-20160303'
      context: .
      dockerfile: Dockerfiles-php/8.2/Dockerfile-alpine
    volumes:
      - ./:/var/www/html