name: Build and deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: php-modules

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Dockerfiles-php/5.6/Dockerfile-alpine
            IMAGE: php:5.6-fpm-alpine
            NAME: 5.6-alpine
            PHP_BUILD_VERSION: 5.6
            PHP_EXTENSION_DIR: '/usr/local/lib/php/extensions/no-debug-non-zts-20131226'

          - dockerfile: Dockerfiles-php/7.0/Dockerfile-alpine
            IMAGE: php:7.0-fpm-alpine
            NAME: 7.0-alpine
            PHP_BUILD_VERSION: "7.0"
            PHP_EXTENSION_DIR: '/usr/local/lib/php/extensions/no-debug-non-zts-20151012'

          - dockerfile: Dockerfiles-php/7.1/Dockerfile-alpine
            IMAGE: php:7.1-fpm-alpine
            NAME: 7.1-alpine
            PHP_BUILD_VERSION: "7.1"
            PHP_EXTENSION_DIR: '/usr/local/lib/php/extensions/no-debug-non-zts-20160303'

          - dockerfile: Dockerfiles-php/7.2/Dockerfile-alpine
            IMAGE: php:7.2-fpm-alpine
            NAME: 7.2-alpine
            PHP_BUILD_VERSION: "7.2"
            PHP_EXTENSION_DIR: '/usr/local/lib/php/extensions/no-debug-non-zts-20160303'

          - dockerfile: Dockerfiles-php/7.3/Dockerfile-alpine
            IMAGE: php:7.3-fpm-alpine
            NAME: 7.3-alpine
            PHP_BUILD_VERSION: "7.3"
            PHP_EXTENSION_DIR: '/usr/local/lib/php/extensions/no-debug-non-zts-20160303'

          - dockerfile: Dockerfiles-php/7.4/Dockerfile-alpine
            IMAGE: php:7.4-fpm-alpine
            NAME: 7.4-alpine
            PHP_BUILD_VERSION: "7.4"
            PHP_EXTENSION_DIR: '/usr/local/lib/php/extensions/no-debug-non-zts-20160303'

          - dockerfile: Dockerfiles-php/8.0/Dockerfile-alpine
            IMAGE: php:8.0-fpm-alpine
            NAME: 8.0-alpine
            PHP_BUILD_VERSION: "8.0"
            PHP_EXTENSION_DIR: '/usr/local/lib/php/extensions/no-debug-non-zts-20160303'

          - dockerfile: Dockerfiles-php/8.1/Dockerfile-alpine
            IMAGE: php:8.1-fpm-alpine
            NAME: 8.1-alpine
            PHP_BUILD_VERSION: "8.1"
            PHP_EXTENSION_DIR: '/usr/local/lib/php/extensions/no-debug-non-zts-20160303'

          - dockerfile: Dockerfiles-php/8.2/Dockerfile-alpine
            IMAGE: php:8.2-fpm-alpine
            NAME: 8.2-alpine
            PHP_BUILD_VERSION: "8.2"
            PHP_EXTENSION_DIR: '/usr/local/lib/php/extensions/no-debug-non-zts-20160303'

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          file: ${{ matrix.dockerfile }}
          build-args: |
            IMAGE=${{ matrix.IMAGE }}
            PHP_BUILD_VERSION=${{ matrix.PHP_BUILD_VERSION }}
            PHP_EXTENSION_DIR=${{ matrix.PHP_EXTENSION_DIR }}
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.NAME }}
          cache-from: type=gha,mode=max,${{ runner.os }}-${{ matrix.NAME }}
          cache-to: type=gha,mode=max,${{ runner.os }}-${{ matrix.NAME }}